# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3df24a50f313cd3d1b41edf33db09d1e5801663db31c1f3e6eb6805539561e020e05b6d850998e77e4dccbbf45f8a6c34e42ef7213f9bfbb86d42943982015

test:
  secret_key_base: 09c0b6165b47fd2e6cb7b4453fb31889d9e199f101773bc77c86800d547b266c1f45618ed6aff2ca7914ed228e30c53c14416fd389a7ed58ab9dd666012a2cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
