user:
  max_name_length: 50
  max_email_length: 255
  min_password_length: 6
  per_page: 12
  password_reset_time: 2
  take: 6
  lorem: 5
helpers:
  max_size: 80
users_form:
  size: 50
micropost:
  max_content_length: 150
  post_per_page: 5
picture:
  size: 5
